crime_category_list = [
    "harassment",
    "sex",
    "domestic",
    "sexual battery",
    "domestic dispute",
    "stalking",
    "criminal mischief",
    "fraud",
    "reckless endangerment",
    "leaving scene.",
    "violating court order",
    "probation violation",
    "handicap parking",
    "indecent exposure",
    "false information",
    "public intoxication",
    "animal cruelty",
    "animal neglect",
    "coercion",
    "guns",
    "evading police",
    "property destruction",
    "sexual assault",
    "child support",
    "outstanding warrant",
    "dui",
    "stolen possession",
    "trespassing",
    "privacy invasion",
    "failure to appear",
    "domestic violence",
    "hit-and-run",
    "assault",
    "resisting officer",
    "dogfighting",
    "obstruction",
    "interfering with police",
    "pimping",
    "public urination",
    "child abuse",
    "theft",
    "disorderly conduct",
    "resisting arrest",
    "drugs",
    "alcohol",
    "burglary",
    "battery",
    "attempted murder",
    "breach of peace",
    "evading arrest",
    "weapon",
    "manslaughter",
    "gambling",
    "reckless driving",
    "solicitation",
    "animal abuse",
    "murder",
    "false name",
    "traffic warrants",
    "rape",
    "license",
    "disturbing the peace"
]